---
- name: Execute the shellscript 
  hosts: workers
  become: true
  tasks: 
    # - name: remove the directory
    #   file: 
    #     path: /root/shellscript
    #     state: absent
    - name: Create a directory 
      file: 
        path: /root/shellscript
        state: directory
        mode: 0755
    - name: pwd folder shellscript
      command: pwd
    # - name: copy the shellscript to the remote server
    #   copy:
    #     src: shellscript/create-folder.sh
    #     dest: /root/shellscript/
    #     mode: '0755'  

    - name: Copy the shellscript to the remote server
      copy:
        src: ../shellscript/createfolder.sh  # Adjust this path according to the actual location
        dest: /root/shellscript/
        mode: '0755'

    # - name: Execute the shellscript 
    #   command: /bin/bash /root/shellscript/createfolder.sh  
    #   args:
    #     creates: /root/shellscript/createfolder.sh
    - name: Execute the shellscript 
      command: /bin/bash /root/shellscript/createfolder.sh