---
- name: Deploy Docker container with variables
  hosts: workers
  become: true
  vars:
    docker_image: "{{ docker_image }}" # Ensure this variable is passed or defined elsewhere
    docker_container_name: "{{ docker_container_name }}" # Ensure this variable is passed or defined elsewhere
    docker_port: "{{ expose_port }}:{{ docker_port }}" # Adjusted for clarity, ensure 'expose' and 'docker_port' are defined
  tasks:
    # - name: Deploy Docker container
    #   docker_container:
    #     name: "{{ docker_container_name }}"
    #     image: "{{ docker_image }}"
    #     state: started
    #     ports:
    #       - "{{ docker_port }}"
    #     restart_policy: always
    - name: run docker with command docker run -d
      command: docker run -d -p {{ expose_port }}:{{ docker_port }} {{ docker_image }}
      register: docker_run
      failed_when: docker_run.rc != 0    
    - name: Ensure Docker container is running
      command: docker ps | grep "{{ docker_container_name }}"
      register: docker_ps
      failed_when: docker_ps.rc != 0    
